# TODO: fix later
version: "3"
services:
  app:
    container_name: "gobel-api"
    build:
        context: "./app"
        dockerfile: "Dockerfile.ci"
    ports:
      - "8080:8080"
    command: ./gobel-api